apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-connect-ui
  name: kafka-connect-ui
spec:
  ports:
  - name: "8003"
    port: 8003
    targetPort: 8000
  selector:
    io.kompose.service: kafka-connect-ui
status:
  loadBalancer: {}
