apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-rest-proxy
  name: kafka-rest-proxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-rest-proxy
    spec:
      containers:
      - env:
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: kafka1:9092
        - name: KAFKA_REST_HOST_NAME
          value: kafka-rest-proxy
        - name: KAFKA_REST_LISTENERS
          value: http://0.0.0.0:8082/
        - name: KAFKA_REST_SCHEMA_REGISTRY_URL
          value: http://kafka-schema-registry:8081/
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value: zoo1:2181
        image: confluentinc/cp-kafka-rest:4.1.0
        name: kafka-rest-proxy
        ports:
        - containerPort: 8082
        resources: {}
      hostname: kafka-rest-proxy
      restartPolicy: Always
status: {}
