apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry-ui
  name: schema-registry-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: schema-registry-ui
    spec:
      containers:
      - env:
        - name: PROXY
          value: "true"
        - name: SCHEMAREGISTRY_URL
          value: http://kafka-schema-registry:8081/
        image: landoop/schema-registry-ui:0.9.4
        name: schema-registry-ui
        ports:
        - containerPort: 8000
        resources: {}
      hostname: kafka-schema-registry-ui
      restartPolicy: Always
status: {}
